name: Build Angular

on:
  push:
    branches: [ CI ]

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # - run: npm install
    - run: npm ci
    - run: npm run build --if-present
